### ISSUE TITLE
Please provide hg38 version of reference files

### ISSUE THREAD

**Issue by cboursnell** [hartwigmedical/gridss-purple-linx#3] opened 2019-10-09 10:39 UTC
Thanks!

**Comment by d-cameron** [comment] 2019-10-17 00:52
This is currently blocking on having enough samples processed with hg38 to construct a good hg38 GRIDSS panel of normals. We're intended to reprocess 100 samples on hg38 but it's likely to be a month or two before this is complete and we can generate a PON.

**Comment by cboursnell** [comment] 2019-10-22 15:13
Thanks for working on this! Is there a way you could provide a tool for me to generate the PON myself? I have over 500 WGS samples aligned to hg38

**Comment by ameynert** [comment] 2019-10-22 15:49
I have several hundred hg38 WGS as well. Would be worth @cboursnell and myself both doing this and comparing the panels for consistency?

**Comment by d-cameron** [comment] 2019-10-22 23:09
>Is there a way you could provide a tool for me to generate the PON myself? 

This is covered in the GRIDSS README: https://github.com/PapenfussLab/gridss#how-do-i-create-the-panel-of-normals-required-by-gridss_somatic_filterr

**Comment by p-priestley** [comment] 2019-10-22 23:15
FYI - I just looked at the impact of our v37 PON on our internal samples.   The PON filters a median of ~60 variants per sample.     Most are short deletions, short duplications and single breakends

We are starting to work on creating a hg38 PON internally based on 100 samples which will deliver the majority of the benefit.   I do not have a timeline for this at this stage, sorry.

**Comment by ameynert** [comment] 2020-01-16 10:49
Any update on this?

**Comment by ohofmann** [comment] 2020-01-16 10:53
Daniel, Peter, any point in us running GRIDSS hg38 on ~100 normals from our side?

**Comment by ameynert** [comment] 2020-01-30 10:15
@cboursnell Did you ever end up producing an hg38 panel? I've been attempting one on my end; have successfully generated the normal VCFs but the actual panel generation is throwing errors.

**Comment by cboursnell** [comment] 2020-02-03 13:18
@ameynert Yes I created a panel of normals for hg38, but only managed to generate it with 150 samples at a time. Any more and the process failed. However the gridss-purple-linx dbs resource contains many other files that are in hg19 for example knownFusionPairs and germlineHetPon. It's these that I would like in hg38 format as well

**Comment by ameynert** [comment] 2020-02-03 14:03
@cboursnell I've been working on the other files as well - hg38 versions of a number of them can be found on the Hartwig resource download site under the names of other tools e.g. AMBER, COBALT. I lifted over some others. I still need the dbs/ensembl_data_cache files, which I was planning to try and regenerate on Ensembl v99, and the dbs/sv/heli_rep_origins.bed file - could lift over, but would be better if it's been re-generated on hg38. Here are my notes:

```
dbs/
	ensembl_data_cache/
		ensembl_gene_data.csv
		ensembl_protein_features.csv
		ensembl_trans_exon_data.csv
		ensembl_trans_splice_data.csv
	gc/
		GC_profile.hg38.1000bp.cnp (3088281) (https://nc.hartwigmedicalfoundation.nl/index.php/s/a8lgLsUrZI5gndd?path=%2FHMFTools-Resources%2FCobalt)
	germline_het_pon_h38/
		GermlineHetPon.hg38.bed (1348931) (https://nc.hartwigmedicalfoundation.nl/index.php/s/a8lgLsUrZI5gndd?path=%2FHMFTools-Resources%2FAmber2)
		GermlineHetPon.hg19.vcf.gz (1338094) (https://nc.hartwigmedicalfoundation.nl/index.php/s/a8lgLsUrZI5gndd?path=%2FHMFTools-Resources%2FAmber3)
	gridss/
		ENCFF001TDO.bed -> hg38-blacklist.v2.bed (https://github.com/Boyle-Lab/Blacklist/blob/master/lists/hg38-blacklist.v2.bed.gz)
		pon3792v1/ - to be generated from local cohort
			gridss_pon_breakpoint.bedpe
			gridss_pon_single_breakend.bed
	knowledgebases/
		output/  - no locus info - all 3 files copied directly from hg19 bundle
			knownFusionPairs.csv
			knownPromiscuousFive.csv
			knownPromiscuousThree.csv
	repeatmasker/
		hg38.fa.out (5622519) (http://www.repeatmasker.org/genomes/hg38/RepeatMasker-rm405-db20140131/hg38.fa.out.gz)
	sv/
		fragile_sites_hmf.csv (21) - this is from the Hartwig metastatic paper. Found the original in the supplementary info (https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-019-1689-y/MediaObjects/41586_2019_1689_MOESM1_ESM.pdf). Best bet is to lift over to hg38.
		
			grep -v Chromosome ../../../hg19/dbs/sv/fragile_sites_hmf.csv | sed -e 's/,/\t/g' | cut -f 1,2,3,5 | awk '{ print "chr" $0 }' > fragile_sites_hmf_hg19.bed
			liftOver fragile_sites_hmf_hg19.bed /exports/igmm/eddie/NextGenResources/liftOverResources/hg19ToHg38.over.chain fragile_sites_hmf_hg38.bed fragile_sites_hmf_unmapped.bed
			head -n 1 ../../../hg19/dbs/sv/fragile_sites_hmf.csv > fragile_sites_hmf_hg38.csv
			awk '{ print $1 "," $2 "," $3 "," $3 - $2 "," $4 }' fragile_sites_hmf_hg38.bed >> fragile_sites_hmf_hg38.csv
		
		heli_rep_origins.bed - not sure. Replication timing from ENCODE seems likely. Reference 36 in the GRIDSS/PURPLE/LINX biorxiv paper is for the 2012 ENCODE paper.
		
		line_elements.csv (125) - Supplementary Table 5 from https://www.biorxiv.org/content/10.1101/179705v3 (PCAWG retro-transposon paper) - liftOver probably makes the most sense
		
			grep -v Chromosome ../../../hg19/dbs/sv/line_elements.csv | sed -e 's/,/\t/g' | awk '{ print "chr" $0 }'> line_elements_hg19.bed
			liftOver line_elements_hg19.bed /exports/igmm/eddie/NextGenResources/liftOverResources/hg19ToHg38.over.chain line_elements_hg38.bed line_elements_unmapped.bed
		
			Sanity check against RepeatMasker
			grep chr ../repeatmasker/hg38.fa.out | awk '{ print $5 "\t" $6 "\t" $7 "\t" $11 }' > repeat_masker.bed
			bedtools intersect -a line_elements_hg38.bed -b repeat_masker.bed -wa -wb > repeat_masker_intersect.txt
			cut -f 2 repeat_masker_intersect.txt | uniq | wc -l
			
			73 mapped - 4 mapped to two LINE elements. Try extending the search area a little to each side - 1kbp.
			
			cut -f 1,2 ../../../../reference/hg38.fa.fai > ../../../../reference/hg38.genome
			bedtools slop -g ../../../../reference/hg38.genome -b 1000 -i line_elements_hg38.bed > line_elements_hg38_plus1kbp.bed
			bedtools intersect -a line_elements_hg38_plus1kbp.bed -b repeat_masker.bed -wa -wb | grep LINE | awk '{ print $0 "\t" $2 - $6 "\t" $3 - $7 }' > repeat_masker_1kbp_intersect.txt
			cut -f 2 repeat_masker_1kbp_intersect.txt | uniq | wc -l
			
			102 mapped - 73 more than once - Use the new coordinates of the Repeat Masker LINE element closest (either by start or end coordinate) to where they are found.
			
			R
			x = read.table("repeat_masker_1kbp_intersect.txt", col.names=c("chr_lo", "start_lo", "end_lo", "name", "chr_rm", "start_rm", "end_rm", "type_rm", "start_df", "end_df"), colClasses=c("character", "numeric", "numeric", "NULL", "NULL", "numeric", "numeric", "NULL", "numeric", "numeric"))
			x$start_df = abs(x$start_df)
			x$end_df = abs(x$end_df)
			x$min_df = x$start_df
			x$min_df[x$end_df < x$start_df] = x$end_df[x$end_df < x$start_df]
			
			y = aggregate(x$min_df, by = list("chr_lo" = x$chr_lo, "start_lo" = x$start_lo, "end_lo" = x$end_lo), min)
			x$closest = 0
			for (i in seq(102)) { x$closest[x$chr_lo == y$chr_lo[i] & x$start_lo == y$start_lo[i] & x$end_lo == y$end_lo[i] & x$min_df == y$x[i] ] = 1 }
			
			y = subset(x, x$closest == 1, select=c("chr_lo", "start_rm", "end_rm"))
			y$type = "Paper"
			colnames(y) = c("Chromosome", "PosStart", "PosEnd", "Type")
			write.table(y, "line_elements_hg38.csv", col.names=T, row.names=F, quote=F, sep=",")
			
		viral_host_ref.csv (1613) - no locus info - copied directly from hg19 bundle
refgenomes/
	hg38/
		hg38.dict
		hg38.fasta
		hg38.fasta.fai
		hg38.len
			awk '{ print $1 "\t" $1 "\t" $2 }' hg38.fasta.fai | sed -e 's/^chr//' > hg38.len
	human_virus/ - no human info - copied directly from hg19 bundle
```

**Comment by cboursnell** [comment] 2020-02-05 13:40
@ameynert That's great! Really useful. When you're done if you could put all the files together you could upload it somewhere. I ran the PON generation again with more memory on 600 patients and it completed just fine and produced a 1.3GB output vcf file.

**Comment by ameynert** [comment] 2020-02-05 13:45
@cboursnell Fantastic - I only have 82 in the panel generated just now and I can't share it due to governance restrictions, but put together the rest of my files with yours if that's shareable and we'll have a proper resource bundle.

**Comment by cboursnell** [comment] 2020-02-06 11:49
The output of the PON has all SVs with occurrences of >=1. What do you think I should filter it by? n >=6? That would be 1%.

**Comment by p-priestley** [comment] 2020-02-06 11:55
1% is very high for a SV PON.    I think we used 3 or more out of ~3500 samples for our 37 PON.   Perhaps 2+ would be appropriate for a 600 PON.   Please make sure all samples are unique individuals though

FYI - We are working towards this internally also.  I expect within a month or so we may be able to provide a good PON ourselves

**Comment by jonbaber** [comment] 2020-02-14 03:40
Hi All, 

We have recently discovered an issue with our COBALT/PURPLE GCProfile in HG38. It was originally generated with an alt enabled ref genome which set the mappability of some regions to zero, including the full HLA region and the region surrounding ERBB2. We have regenerated the file using a "no alt analysis set" version of the hg38 assembly without alt configs. 

I will ask @d-cameron to update this thread once the docker image is updated. 

Regards, Jon

**Comment by ohofmann** [comment] 2020-02-15 00:04
Jon, thanks for the heads up. We've been debugging cases of het2hom blocks in primary genome build regions with matching ALTs for the last two weeks; I _thought_ this was a case of us not post-processing alignments correctly and AMBER ignoring reads with the `supplementary_alignment` flag. Are those two potentially related or are we chasing a different issue?

Cheers, Oliver

**Comment by p-priestley** [comment] 2020-02-17 04:06
Hi Oliver, this could well be the problem.    Please try cobalt with the new GCProfile file, and please also make sure you are aligning to the analysis_set genome with your mapper.

**Comment by ohofmann** [comment] 2020-02-17 23:50
Hi Peter, can I confirm - you expect alignments against a no-ALT hg38? We are routinely [using a reference with ALTs](http://bcb.io/2015/09/17/hg38-validation/) and would have to re-align prior to running PURPLE.

**Comment by d-cameron** [comment] 2020-02-17 23:58
@ohofmann Are you using an alt-aware bwa index, or just the standard bwa index?

**Comment by ohofmann** [comment] 2020-02-17 23:59
We are following Heng's best practice and use bwa-mem with an alt-aware index.

**Comment by p-priestley** [comment] 2020-02-18 00:21
As far I understand alt aware mapping I expect this to work ok, but we have not tested explicitly

**Comment by ameynert** [comment] 2020-03-19 14:27
I've been attempting to run the Docker on hg38-aligned samples using the resource bundle I built and my local GRIDSS PON. I've built it in a Singularity sandbox, and have run into the following:

* repeat annotation falls over on the HLA contigs because of the way the R script is separating the BEALN field (fixed by doing a separate on '|' then an extract on the last ':' in the locus, /opt/gridss/gridss_annotate_insertions_repeatmaster.R line 90)
* hg19 is hard-coded into the loading of the BSgenome package (/opt/gridss/libgridss.R line 8)
* Purple throws an exception at the decoy/alt contigs:

```
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant com.hartwig.hmftools.common.genome.chromosome.HumanChromosome._Un_JTFH01001983v1_decoy
at java.lang.Enum.valueOf(Enum.java:238)
```

I threw up my hands at that point and decided to just filter my input BAMs against chr1-22+X+Y first, but if the tool is only going to work on those contigs could there be an option to ignore anything that doesn't match them? Filtering the input BAMs is slow and takes up almost double the disk space.

**Comment by d-cameron** [comment] 2020-03-20 01:52
We're still working on getting a proper hg38 release. Those first two issues have already been fixed in GRIDSS (https://github.com/PapenfussLab/gridss/issues/306, https://github.com/PapenfussLab/gridss/commit/ca85c5f00e2dff926bd74d2a7c77360f7763c37c), but we haven't pushed up a new gridss-purple-linx package as we were intended to do so in conjuction with full hg38 support.

We just started running samples on hg38 last week so I'm hoping to have a new fully regression tested release with hg38 support before the end of next month.

**Comment by ohofmann** [comment] 2020-03-20 01:55
Thanks for the update!

**Comment by ameynert** [comment] 2020-03-20 09:11
Thanks @d-cameron really appreciate the work being put in on this. Happy to beta test the container and your hg38 bundle when it's ready.

**Comment by DarioS** [comment] 2020-05-01 05:00
Another intriguing opportunity for a panel-of-normals is [gnomAD-SV](https://gnomad.broadinstitute.org/downloads#v2-structural-variants) which is derived from 10847 whole genomes. But, it's only offered for hg19 and doesn't even fully conform to the definition of VCF.

**Comment by ohofmann** [comment] 2020-05-25 01:40
Going to put our hands up to also happily test early versions of it.

**Comment by nvolkovaGEL** [comment] 2020-06-26 12:44
Hi, we're also very keen to test the hg38 version with your or our own PoN, is there any update on it? Thanks!

**Comment by p-priestley** [comment] 2020-06-28 05:30
Sorry with the delay on this.   We have been making further improvements on our tools these last months ahead of running at scale on hg38, but these are done now, and this is very much on our short term agenda.    My ETA would be end of July.

**Comment by jonbaber** [comment] 2020-08-24 05:08
Hi, 

HG38 versions of the resources are all now available from our download [portal](https://resources.hartwigmedicalfoundation.nl/)

Regards, Jonathan

**Closed** 2020-10-21 23:13 UTC

**Comment by DanielNaro** [comment] 2022-10-04 14:16
Hi,
I had downloaded this file previously from this portal, but now I cannot find it. Was it removed/renamed? Is there another way to get it?
Regards,

**Comment by ameynert** [comment] 2022-10-05 15:56
@DanielNaro Which file are you after in particular? I can still see some of the hg38 resources at the portal.

**Comment by charlesshale** [comment] 2022-10-09 20:03
Hi Daniel,

All GHCh38 resource files for our pipeline can be found in the zipped TAR files in HMFTools-Resources -> DNA-Resources.
